site_name: WhiteTreeBible - Blog
site_description: A blog about faith, technology, and life
site_url: https://blog.whitetreebible.com

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - blog:
      blog_dir: blog
      post_dir: "{blog}/posts"
      post_date_format: medium
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
      archive_name: Archive
      archive_date_format: yyyy
      archive_url_date_format: yyyy
      categories_name: Categories
      categories_url_format: "category/{slug}"
      pagination_per_page: 10
      authors_file: "{blog}/.authors.yml"
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

nav:
  - Home: https://whitetreebible.com
  - Tools:
    - Connections: https://connections.whitetreebible.com
    - Blog: https://blog.whitetreebible.com/blog
  - About:
    - About Us: https://whitetreebible.com/about/about-us.md
    - Get Updates: https://whitetreebible.com/about/get-email-updates.md
    - Support Us: https://whitetreebible.com/about/support-us.md
  - Blog:
    - Blog: blog/index.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/whitetreebible
