authors:
  rswhiting:
    name: Robert Whiting
    description: Software engineering manager, apprentice of Jesus, and lifelong learner exploring the intersection of faith and technology.
    avatar: https://github.com/rswhiting.png
    url: https://rswhiting.com/